google/auth/_helpers.py
google/auth/compute_engine/__init__.py
google/auth/compute_engine/_metadata.py
pylintrc.tests
tests/compute_engine/test__metadata.py
tests/test__helpers.py

/cc @elibixby (original author)

Add compute engine metadata client

---

google/oauth2/_client.py
tests/oauth2/test__client.py

Add google.oauth2._client

---

.travis.yml
CHANGELOG.rst
README.rst

Release v0.0.1

---

docs/conf.py
google/auth/transport/__init__.py
google/auth/transport/urllib3.py
tests/transport/test_urllib3.py
tox.ini

Implementation of the plan detailed over at #15.

Add urllib3 AuthorizedHttp

---

docs/reference/google.auth.credentials.rst
docs/reference/google.auth.rst
google/auth/_helpers.py
google/auth/credentials.py
tests/test__helpers.py
tests/test_credentials.py

@nathanielmanistaatgoogle this is the section you indicated you wanted to give input on. PTAL.

Add google.auth.credentials - the public interfaces for credentials

---

google/auth/jwt.py
tests/data/service_account.json
tests/test_jwt.py

Add JWT credentials

---

google/auth/app_engine.py
tests/test_app_engine.py

Add app engine credentials

---

google/auth/_default.py
google/auth/app_engine.py
google/auth/compute_engine/_metadata.py
tests/compute_engine/test__metadata.py
tests/test__default.py
tests/test_app_engine.py

Resolves #47.
Additionally moves GCE's project id detection into `_metadata` to keep things consistent.

Add App Engine credentials to google.auth.default

---

google/auth/compute_engine/_metadata.py
google/auth/compute_engine/credentials.py
system_tests/test_compute_engine.py
system_tests/test_service_account.py
tests/compute_engine/test_credentials.py

Add compute engine system tests

---

google/auth/credentials.py
tests/test_credentials.py

This will make it easy to remove some code / branches in google-cloud-python.

Add with_scopes_if_required helper

---

docs/conf.py
docs/reference/google.auth.transport.grpc.rst
docs/reference/google.auth.transport.rst
docs/requirements-docs.txt
google/auth/transport/grpc.py
scripts/run_pylint.py
system_tests/nox.py
system_tests/test_grpc.py
tests/transport/test_grpc.py
tox.ini

@bjwatson @geigerj please review, as this will replace all of [`gax.auth`](https://github.com/googleapis/gax-python/blob/master/google/gax/auth.py) and most of [`gax.grpc`](https://github.com/googleapis/gax-python/blob/master/google/gax/grpc.py).
@nathanielmanistaatgoogle PTAL to verify grpc usage.

Add grpc transport

---

google/auth/_default.py
google/auth/environment_vars.py
tests/test__default.py

Add support for the GCLOUD_PROJECT environment variable

---

docs/index.rst
docs/user-guide.rst

These are staged here: http://temp.theadora.io/google-auth/index.html
Resolves #44.

Add basic user guide

---

docs/reference/google.oauth2.id_token.rst
docs/reference/google.oauth2.rst
google/oauth2/id_token.py
tests/oauth2/test_id_token.py

Resolves #39 and the v1.0.0 milestone.

Add ID token verification helpers.

---

google/auth/_helpers.py
google/auth/jwt.py
google/oauth2/id_token.py
tests/oauth2/test_id_token.py
tests/test__helpers.py

* Fix call to `transport.Request`.
* Make jwt support base64 strings lacking padding characters.

Fix ID token verification

---

google/auth/transport/grpc.py
tests/transport/test_grpc.py

Make secure_authorized_channel pass kwargs to grpc.secure_channel

---

google/auth/app_engine.py
google/auth/credentials.py
google/auth/jwt.py
google/oauth2/service_account.py
tests/oauth2/test_service_account.py
tests/test_app_engine.py
tests/test_jwt.py

Add Signing.singer_email

---

google/auth/crypt.py
tests/test_crypt.py

Add crypt.Signer.from_service_account_file

---

google/auth/app_engine.py
google/auth/crypt.py

Add app_engine.Signer

---

docs/_static/custom.css
docs/conf.py
docs/reference/google.oauth2.flow.rst
docs/reference/google.oauth2.rst
google/oauth2/flow.py
setup.py
tests/data/client_secrets.json
tests/oauth2/test_flow.py
tox.ini

Add google.oauth2.flow - utility for doing OAuth 2.0 Authorization Flow

---

docs/reference/google.auth.iam.rst
docs/reference/google.auth.rst
google/auth/crypt.py
google/auth/iam.py
tests/test_iam.py

Add IAM signer

---

google/auth/app_engine.py
tests/test_app_engine.py

Fix issue where GAE Signer erroneously returns a tuple from sign()

---

google/auth/credentials.py
google/auth/transport/grpc.py
system_tests/test_grpc.py
tests/transport/test_grpc.py
tox.ini

Fix gRPC to call credentials.before_request

---

google/auth/_service_account_info.py
google/auth/app_engine.py
google/auth/crypt.py
google/auth/iam.py
tests/oauth2/test_service_account.py
tests/test__service_account_info.py
tests/test_app_engine.py
tests/test_crypt.py
tests/test_iam.py
tests/test_jwt.py

Create abstract Verifier and Signer, remove key_id hack from App Engine and IAM signers

---

google/auth/jwt.py
google/oauth2/service_account.py
system_tests/test_grpc.py
tests/oauth2/test_service_account.py
tests/test_jwt.py

Remove one-time token behavior of JWT Credentials

---

google/auth/jwt.py
google/oauth2/service_account.py
system_tests/test_grpc.py
tests/oauth2/test_service_account.py
tests/test_jwt.py

This change made possible by making `Signing.signer` public.

Add jwt.Credentials.from_signing_credentials, remove serivce_account.Credentials.to_jwt_credentials

---

google/auth/transport/grpc.py
google/auth/transport/requests.py
google/auth/transport/urllib3.py
google/oauth2/oauthlib.py

Add helpful error messages when importing optional dependencies

---

MANIFEST.in
setup.py

@lukesneeringer @dhermes FYI, this probably needs to be double-checked in google-cloud as well.

Fix inclusion of tests package in setup.py

---

additional_packages/google_auth_oauthlib/google_auth_oauthlib/flow.py
additional_packages/google_auth_oauthlib/tests/test_flow.py
additional_packages/google_auth_oauthlib/tox.ini
tox.ini

Add InstalledAppFlow

---

google/auth/jwt.py
google/oauth2/service_account.py
tests/oauth2/test_service_account.py

Add service_account.Credentials.with_claims

---

google/auth/_helpers.py
google/auth/credentials.py
google/auth/jwt.py
tests/compute_engine/test_credentials.py
tests/oauth2/test_credentials.py
tests/test_app_engine.py
tests/test_credentials.py

Resolves #141.
/cc @vchudnov-g

Add a consistent 5 minute clock skew accomodation

---

google/auth/_cloud_sdk.py
system_tests/nox.py
tests/data/cloud_sdk.cfg
tests/data/cloud_sdk_config.json
tests/test__cloud_sdk.py
tests/test__default.py

Use "gcloud config config-helper" to read the project ID from the Google Cloud SDK

---

google/auth/compute_engine/_metadata.py
google/auth/environment_vars.py
tests/compute_engine/test__metadata.py

The goal here is to make it possible for a user of a binary that depends on
this library (eg the google cloud SDK) to be able to customize where it looks
for the GCE metadata service. (An adventurous user can already customize the
GCE metadata service location via the existing global vars in this library.)
The only bit of awkwardness here is really the test: since this is a top-level
statement, reloading is the only way to ensure it works.
PTAL @jonparrott
(and why yes I DID just completely copy-paste the commit description from the oauth2client PR.)

Allow customizing the GCE metadata service address via an env var.

---

google/auth/jwt.py
setup.py
system_tests/test_grpc.py
tests/test_jwt.py

Resolves #136.
Note: this adds a new dependency on `cachetools`.

Add jwt.OnDemandCredentials

---

google/oauth2/credentials.py
google/oauth2/service_account.py
tests/oauth2/test_credentials.py
tests/oauth2/test_service_account.py

Expose id_token in OAuth 2.0 credentials

---

google/auth/credentials.py
tests/test_app_engine.py
tests/test_credentials.py
tests/test_iam.py
tests/transport/test_grpc.py

Previously, the clock skew adjusted in the wrong direction. It would cause us to consider credentials whose expiration time had already passed according to the system clock to still be sent to the server. This is the opposite of what we wanted to happen. This fixes it so that we report that credentials are expired slightly before the system clock thinks they've expired.

Fix clock skew calculations

---

google/auth/transport/_http_client.py
tests/transport/compliance.py

Fix missing timeout argument for http.client transport

---

google/auth/_cloud_sdk.py
tests/test__cloud_sdk.py

- Fix for shell command call "subprocess.check_output(_CLOUD_SDK_CONFIG_COMMAND...)".
- Previously, it would trigger an error "WindowsError: [Error 2] The system cannot find the file specified". A workaround was to specify the env variable GCLOUD_PROJECT.
- With this patch, "gcloud" default project is successfully retrieved.

Fix retrieval of default project ID on Windows

---

google/auth/_default.py
tests/test__default.py

Fixes #161 according to @jonparrott's recommendation

Fix 161: Add error message to handle case of empty string for GOOGLE_APPLICATION_CREDENTIALS

---

google/auth/compute_engine/credentials.py
google/auth/credentials.py
tests/compute_engine/test_credentials.py
tests/test_credentials.py

Not all subclasses of 'Scoped' can sanely implement `with_scopes` (e.g, on GCE the scopes are hard-wired in when creating the GCE node).
Make `Scoped` derive from `ReadOnlyScoped`, adding the `with_scopes` method.
Make GCE's `Credentials` class derive from `ReadOnlyScoped`.
Closes #194.

Move read-only methods of 'Scoped' into new interface, 'ReadOnlyScoped'.

---

google/oauth2/credentials.py
tests/oauth2/test_credentials.py

This is an issue when using spanner client APIs. https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4010. Having OAuth2 credentials inherit from ReadOnlyScoped instead of Scoped will fix that.

Fix OAuth2 credentials to inherit from ReadOnlyScoped instead of Scoped.

---

README.rst
docs/index.rst

As requested in b/64770713.
The package is referenced in some of the BigQuery documentation; considering the structure of the documents it might be better to add the link to python setup guide here.

Updated the doc with python setup guide

---

setup.py

Instead, rely on pyasn1-modules to pull the appropriate version.

Drop direct pyasn1 dependency

---

.gitignore
google/auth/crypt/_cryptography_rsa.py
google/auth/crypt/_python_rsa.py
google/auth/crypt/base.py
google/auth/crypt/rsa.py
tests/crypt/test__cryptography_rsa.py
tests/crypt/test__python_rsa.py
tests/test__service_account_info.py
tox.ini

Fixes #183.
NOTE: This change is incomplete. It needs unit tests and a `Verifier` implementation.
Big H/T to @arthurdarcet for the implementation.

Adding `cryptography` Signer.

---

google/oauth2/credentials.py
tests/oauth2/test_credentials.py

Raise a helpful exception when trying to refresh credentials without a refresh token

---

google/auth/compute_engine/__init__.py
google/auth/compute_engine/credentials.py
tests/compute_engine/test_credentials.py

This branch includes:
- a Signer implementation that relies on the IAM API ([signBlob](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob)) using the default Credentials
- a Credentials implementation that provides ID tokens, using the Signer above.

Signer and IDTokenCredentials implementation using default service account on GCE

---

tests/test_jwt.py

Fixes the following test failure under Python 3.7:
```
=================================== FAILURES ===================================
_______________________ test_decode_bad_token_not_base64 _______________________
def test_decode_bad_token_not_base64():
with pytest.raises((ValueError, TypeError)) as excinfo:
jwt.decode('1.2.3', PUBLIC_CERT_BYTES)
>       assert excinfo.match(r'Incorrect padding')
E       AssertionError: Pattern 'Incorrect padding' not found in 'Invalid base64-encoded string: length cannot be 1 more than a multiple of 4'
tests/test_jwt.py:121: AssertionError
======== 1 failed, 280 passed, 4 skipped, 1 deselected in 21.03 seconds ========
```

Allow error text of Python 3.7

---

google/auth/_default.py

In colab and likely other applications, the period is incorrectly bound into the url, which is then invalid and produces a 404
DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or
explicitly create credential and re-run the application. For more
information, please see
https://developers.google.com/accounts/docs/application-default-credentials.

Remove punctuation which becomes part of the url

---

google/auth/impersonated_credentials.py
tests/test_impersonated_credentials.py

Remove logic that current _does not_ `refresh` credentials if `lifetime=` parameter is set.
After this change, if the `lifetime=` is set, it only applies to the actual token returned for the impesonated credentials.  If either the `source_credential` or or `target_credential` expires, a refresh will get called to regenerate a new one.  If a user just wants a non-expiring access_token for the impersonated credentials, they can extract the access_token and `.apply()` headers.

Add autorefresh lifetime for impersonated_redentials

---

CHANGELOG.rst

The 1.6.0 release included Markdown link syntax for the PR's, which doesn't work in reStructuredText. Whilst fixing that I converted all the reference numbers to be links.

Link all the PR's in CHANGELOG

---

google/auth/_default.py
setup.py
tests/test__default.py

Handle ImportError when importing optional dependencies such as app_engine and compute_engine.
No unit tests yet pending input from maintainers.

_default.default() now handles ImportErrors for optional dependencies.

---

google/auth/_helpers.py
google/auth/jwt.py
tests/test__helpers.py

So, I was writing something that used this library to sign JWTs in GCP to authenticate with Vault using the GCP engine. While I was able to generate tokens (parsing them locally) just fine, I was failing authentication with an error regarding illegal byte sequences during base-64 decoding.
Turns out the vault plugin, which is written in Go, uses a [`RawUrlEncoding`](https://golang.org/pkg/encoding/base64/#pkg-variables) to decode the incoming JWT. My tokens were failing to decode because each segment included the `=` padding. Oh.
According to the [RFC 7515](https://tools.ietf.org/html/rfc7515#page-6):
> Base64 encoding [... has] _all trailing '=' characters omitted_ (as permitted by Section 3.2)
> and [is] without the inclusion of any line breaks, whitespace, or other additional
> …

follow rfc 7515 : strip padding from JWS segments

---

google/auth/compute_engine/_metadata.py

This is to address https://github.com/googleapis/google-auth-library-python/issues/211.
I was able to reproduce the issue in App Engine Flex - my repro is an autoscaling application with minimum 1 instance and max 10 instances that makes calls to google.auth.default() on GET requests. Using apache benchmark to scale it up, there was a brief period of time '[Errno 111] Connection Refused' would be intermittently thrown (during the scale up event). Adding this retry has resolved this for me.
This has been tested manually. Please let me know if there are any integration tests I should run first, though this change should be low risk and largely invisible to all users of _metadata.py.
Many Thanks!

Add retry to _metadata.ping()

---

setup.py

I was using `pex` on an application that lists `google-auth` as a dependency and got the following warning:
..../pex/environment.py:330 UserWarning: The `pkg_resources` package was loaded from a pex
vendored version when declaring namespace packages defined by google-auth 1.6.2. The 
google-auth 1.6.2 distribution should fix its `install_requires` to include `setuptools`
So adding `setuptools` as a listed dependency to fix this.
Also making the listing alphabetical.

Fix `pex` warning

---

docs/user-guide.rst

The original wording had me grant Token Creator role to the target account, which didn't work. I think this should clarify.

doc: clarify which SA has Token Creator role

---

setup.py
tox.ini

This should make this library more robust in case of breaking changes in one of
its dependencies.

setup.py: set an upper bound on dependencies version

---

tests/test__default.py
tox.ini

Matches was changed to match with at least pytest4 and from pytest 5.0+ it does not work.

Use new pytest api to keep building with pytest 5

---

README.rst

Hello google package maintainer,
The badges being added to the README in this PR will indicate your compatibility with other google packages. This addresses a set of user bugs which have happened when a user depends on two Cloud libraries (or runtimes that bundle libraries), say A and B, which both depend on library C. If the two libraries require different versions of C, the users can run into issues both when they pip install the libraries, and when they deploy their code. Our compatibility server checks that all libraries we make including this one are self and pairwise compatible as well as not having any deprecated dependencies. The two badges will mark the build for your project green when the latest version available on PyPI and github HEAD respectively meet all compatibility …

add compatibility check badges to README

---

google/oauth2/credentials.py

Use cls parameter instead of explicit `Credentials` reference to allow subclassing

Use cls parameter instead of class

---

docs/index.rst
docs/user-guide.rst
google/auth/impersonated_credentials.py
tests/test_impersonated_credentials.py

Adds support for `impersonated_credentials` to sign and issue IDTokens. 
impersonated_credentials uses IAMCredentials api at its core which also provides interfaces to `generateIDToken()` and `signBlob()`:
- https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts
This PR seesk to add support for those.
Some benefits:  
* makes it easy to get GoogleOIDC tokens
* `Singer` interface allows users to 'generate SignedURLs' too. ref: Issue: https://github.com/googleapis/google-auth-library-python/issues/338
---
The PR at the moment does not have sufficient test coverage (its a solid "C" at 75%).  I'm unsure how to mock the internal request/responses since i used `AuthorizedSession()` internally within `imersonated_credentials.py`.  Any tips or pointers there would let …

Add support for imersonated_credentials.Sign, IDToken

---

docs/reference/google.auth.app_engine.rst
docs/reference/google.auth.compute_engine.credentials.rst
docs/reference/google.auth.compute_engine.rst
docs/reference/google.auth.credentials.rst
docs/reference/google.auth.crypt.rst
docs/reference/google.auth.environment_vars.rst
docs/reference/google.auth.exceptions.rst
docs/reference/google.auth.iam.rst
docs/reference/google.auth.impersonated_credentials.rst
docs/reference/google.auth.jwt.rst
docs/reference/google.auth.rst
docs/reference/google.auth.transport.grpc.rst
docs/reference/google.auth.transport.requests.rst
docs/reference/google.auth.transport.rst
docs/reference/google.auth.transport.urllib3.rst
docs/reference/google.oauth2.credentials.rst
docs/reference/google.oauth2.id_token.rst
docs/reference/google.oauth2.rst
docs/reference/google.oauth2.service_account.rst
docs/reference/google.rst
google/oauth2/_client.py
tests/oauth2/test__client.py

This is to prevent errors when client tries to connect with server and fails to fetch OAuth2 token throwing 'Internal Failure'.
Bug - https://bugs.chromium.org/p/chromium/issues/detail?id=1001206

Add retry loop  for fetching authentication token if any 'Internal Failure' occurs

---

google/oauth2/_client.py
tests/oauth2/test__client.py

As I was saying in [this comment](https://github.com/googleapis/google-auth-library-python/pull/368#issuecomment-553357310)
In some cases response doesn't contain `error_description` field. So the retry won't work. The solution is to look at both `error` and `error_description` fields.

fix: fix check for 'internal_failure' condition

---

.github/release-please.yml

This will allow release-please to propose new releases based on the commit history.
To be merged after #377, which will be the last release with commits not in the conventional commit format.

build: enable release-please

---

google/oauth2/_client.py

The interface of the underlying transport
'google.auth.transport.Request' that makes the token
request does not guarantee the response is encoded. In Python 3, the
non-encoded strings do not have 'decode' attribute. Blindly decoding all
the response could have the token refresh throw here.

fix: in token endpoint request, do not decode the response data if it is not encoded

---

google/oauth2/credentials.py
tests/oauth2/test_credentials.py

This adds a `Storage` base interface class and a `file` module based on `Storage` to save and load credentials.
The `credentials` module was modified to rely on the newer `Storage` class while retaining compatibility.

feat: add `to_json` method to google.oauth2.credentials.Credentials

---

docs/reference/google.auth.crypt.base.rst
docs/reference/google.auth.crypt.rsa.rst
google/oauth2/credentials.py
tests/data/authorized_user.json
tests/oauth2/test_credentials.py

When the 3LO credentials are used, the quota project ("quota_project_id") should be sent on every outgoing request in the x-goog-user-project HTTP header/grpc metadata.

feat: send quota project id in x-goog-user-project for OAuth2 credentials

---

google/auth/transport/requests.py
noxfile.py
tests/transport/test_requests.py

Reverts googleapis/google-auth-library-python#397
Rolling this back as a bug opened on a repo using google-cloud-storage started failing and this seems like the most probable cause. https://github.com/googleapis/docuploader/issues/22

fix: revert "feat: add timeout parameter to AuthorizedSession.request()"

---

docs/reference/google.auth.crypt.base.rst
docs/reference/google.auth.crypt.rsa.rst
google/oauth2/credentials.py
tests/oauth2/test_credentials.py

Reverts googleapis/google-auth-library-python#400
In addition to a comment on the original PR, folks have filed issue #405. Credentials pickled with the previous class definition (with no quota project) cannot be correctly unpickled. Many official docs pages have code to pickle credentials files, so we should make sure this use case is not broken.

Revert "feat: send quota project id in x-goog-user-project for OAuth2 credentials"

---

google/auth/transport/requests.py
noxfile.py
tests/transport/test_requests.py

Fixes #396.
This PR is a replacement for #397 that caused a [bug](https://github.com/googleapis/google-auth-library-python/issues/404) in at least one downstream librariy. It contains additional logic that correctly handles `timeouts` passed as a tuple (the `requests` library support two different timeout forms - [link](https://2.python-requests.org/en/master/user/advanced/#timeouts)).
The first commit is identical to the original PR, and all new logic is contained in the commit(s) that follow.
**MIND:**
A downstream library that is timeout-sensitive might still be affected by the change, because the new explicit timeout parameter changes the semantics of `AuthorizedSession.request()` . The timeout represents the total allowed time for _all_ requests made behind the scenes (e.g. …

feat: add timeout parameter to AuthorizedSession.request()

---

google/auth/compute_engine/_metadata.py
tests/compute_engine/test__metadata.py

Initial fix of issue #211 was done in CL #323, but only for .ping()
This one is adding same behavior & tests for .get() method, as the problem still arises
Resolves: #211

fix: add retry to `google.auth.compute_engine._metadata.get()`

---

google/auth/iam.py
google/auth/impersonated_credentials.py
google/oauth2/_client.py
tests/oauth2/test__client.py

[`google.auth.transport.Request`](https://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.html#google.auth.transport.Request) says that the body should be of type bytes. Some of our code was passing in strings as reported in #318.
In practice this was not causing issues, as the two http transports [requests](https://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.requests.html) and [urllib3](https://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.urllib3.html) are able to handle bodies passed as strings.
Closes #318

fix: always pass body of type bytes to `google.auth.transport.Request`

---

google/auth/jwt.py

Fixes #418.
Use collections.abc.Mapping instead of deprecated collections.Mapping that will be removed with Python 3.9.

fix: make collections import compatible across Python versions

---

google/auth/jwt.py

The coverage report is generated from the unit test session that runs last (3.7), which won't invoke the 'except' clause.

test: add no cover for py2 collections import

---

google/auth/transport/requests.py
tests/transport/test_requests.py

Closes #423. 
Towards https://github.com/googleapis/google-cloud-python/issues/10137
This PR makes a distinction between the Requests transport timeout, i.e. the ``timeout`` parameter, and the total allowed execution time for the `request()` method, i.e. the ``max_allowed_time`` argument. These two are not mixed together anymore.
In other words, if `timeout` is passed in (set to, say, 60 seconds) and an underlying request takes longer, but the times between the bytes received by the socket are all under 60 seconds, the `TimeoutGuard` should **not** kick in and cause a timeout error (the cause of [Storage #10137](https://github.com/googleapis/google-cloud-python/issues/10137)).
`TimeoutGuard` is only affected by ``max_allowed_time``, which is `None` by default, making the guard a no-op.

feat: distinguish transport and execution time timeouts

---

README.rst

* Link to docs on googleapis.dev, not readthedocs
* Edit old repo links to use org googleapis, not GoogleCloudPlatform
Addresses part of #431

docs: link to docs on googleapis, edit old links

---

google/auth/transport/requests.py
tests/transport/test_requests.py

Closes #434.
This PR adds a non-`None` default timeout to `AuthorizedSession.request()` to prevent requests from hanging indefinitely in a default case.
Should help with https://github.com/googleapis/google-cloud-python/issues/10182

feat: add non-None default timeout to AuthorizedSession.request()

---

google/oauth2/id_token.py

The new certificate (https://www.googleapis.com/oauth2/v3/certs) is in a jwk format and it doesn't match the format expected when decoding a jwt here.
https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/jwt.py#L220
A quick fix is to revert this update and continue using the /v1 uri.
The decode() function mentioned above should be fixed to accept jwk format certificates in the future.

Revert "fix: update `_GOOGLE_OAUTH2_CERTS_URL` (#365)"

---

google/auth/transport/_mtls_helper.py
google/auth/transport/requests.py
google/auth/transport/urllib3.py
noxfile.py
system_tests/noxfile.py
system_tests/test_mtls_http.py
tests/conftest.py
tests/transport/test__mtls_helper.py
tests/transport/test_requests.py
tests/transport/test_urllib3.py

This PR adds mTLS ADC support for HTTP (AuthorizedSession and AuthorizedHttp).
go/adc-for-dca-python

feat: add mTLS ADC support for HTTP

---

google/auth/transport/grpc.py

Reverts part of #390.
grpc's documentation states AuthMetadataPlugin's `__call__` should be non-blocking. https://grpc.github.io/grpc/python/grpc.html#grpc.AuthMetadataPlugin.__call__. However, @lidiz of gRPC Python confirms that a separate thread is already spun up for the plugin callback so it will not block the gRPC call (see comment below).
The current implementation of downstream clients results in threads being leaked.
Clients create gRPC channels but do not explicitly close them. See https://github.com/googleapis/google-cloud-python/issues/9457 and https://github.com/googleapis/google-cloud-python/issues/9790. This means associated resources do not get cleaned up.
See https://github.com/googleapis/google-cloud-python/pull/9894 for an example of the changes that need to be made to …

fix: don't use threads for gRPC AuthMetadataPlugin, reverts #390

---

google/auth/_cloud_sdk.py
google/auth/_default.py
google/auth/exceptions.py
google/auth/transport/grpc.py
google/oauth2/credentials.py
system_tests/test_mtls_http.py
tests/oauth2/test_credentials.py
tests/test__cloud_sdk.py

(1) Add `UserAccessTokenCredentials` class which uses `gcloud auth print-access-token` to obtain user account access token. This token is used to access api endpoint when mtls is enforced.
(2) Remove `google.auth._cloud_sdk.load_authorized_user_credentials` since it is a duplicate of `google.oauth2.credentials.from_authorized_user_info`. Also has to remove this to avoid cyclic import problem.

feat: add access token credentials

---

google/auth/compute_engine/credentials.py
system_tests/test_compute_engine.py
tests/compute_engine/test_credentials.py

Fix #479 
`self.expiry` should be a `datetime.datetime` object, treated similar as https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/impersonated_credentials.py#L352

fix: invalid expiry type

---

google/auth/exceptions.py
google/auth/transport/mtls.py
google/auth/transport/requests.py
google/auth/transport/urllib3.py
system_tests/test_mtls_http.py
tests/transport/test_mtls.py

1. This is used to feed `ClientOptions.client_cert_source` with the default client SSL credentials.
Example usage in gapic generated client: https://github.com/arithmetic1728/mtls_grpc_sample/blob/sample/grpc_sample.py#L14
2. Fix the keyword argument `client_cert_callabck` typo in `configure_mtls_channel`.

feat: add default client cert source util

---

google/auth/crypt/es256.py
tests/crypt/test_es256.py

es256 signature should have the raw format instead of asn1 encoded format. Raw format is base64url encoded bytes array (64 bytes) of two integers r, s (each contributes 32 bytes to the array).
Verified the fix works with iap issued id_token in PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/3444

fix: wrong es256 signature format

---

google/auth/impersonated_credentials.py
tests/test_impersonated_credentials.py

gcloud uses httplib2 for the underlying http where response.data is string instead of bytes.

chore: support string type response.data for gcloud

---

tests/transport/test_requests.py

change delta=number to datetime.timedelta(seconds=number)

test: fix usage of tick function so g3 tests can pass

---

google/oauth2/id_token.py

Should catch the `RefreshError` raised by `credentials.refresh(request)`. This should be the cause or at least part of the cause of issue: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3712

fix: catch exceptions.RefreshError

---

google/auth/impersonated_credentials.py

fix: signBytes for impersonated credentials

---

google/auth/impersonated_credentials.py
tests/test_impersonated_credentials.py

(1) For IDTokenCredentials.refresh(self.request), use the provided 
request instead of creating a new one
(2) For impersonated_credentials.Credentials, only refresh the source credentials if it is not 
valid (in other words, expires within _helpers.CLOCK_SKEW=5 minutes). Also we need to remove the `expired` function (because it doesn't support clock skew), so it can fall back to the `expired` function defined in `google.auth.credentials.Credentials` interface which respect the clock skew.

fix: fix impersonated cred for gcloud

---

google/auth/impersonated_credentials.py

Fix the doc: `RefreshError` is raised instead of `DefaultCredentialsError`.

docs: fix impersonated cred exception doc

---

google/oauth2/credentials.py

from #494, 
this PR updated the docstring of ``to_json`` method in the credential so that it points user to ``from_authorized_user_info`` instead of the non-existent ``from_json``

docs: update docstring of to_json() method

---

setup.py

Version 4.0 was the last version to support Python 2 and 3.4. Version 4.1 is compatible with Python 3.5+ only.

fix: narrow acceptable RSA versions to maintain Python 2 compatability

---

setup.py

Related to #528. RSA seems to have released another version without `python_requires` being enforced. This will guard against that for our package.

fix(dependencies): Further restrict RSA versions

---

google/auth/_default.py
tests/data/authorized_user_cloud_sdk_with_quota_project_id.json
tests/test__default.py

If user account cred has 'quota_project_id', ignore the warning.
Implementing http://shortn/_YUlAgzL40H

fix: no warning if quota_project_id is given

---

README.rst
setup.py

Remove 3.4 from the supported versions list. We no longer actively test it and it has been EOL since March. https://www.python.org/downloads/release/python-3410/

docs: remove 3.4 from supported versions list

---

.gitignore
google/auth/iam.py
system_tests/test_service_account.py
tests/compute_engine/test_credentials.py
tests/test_iam.py

Migrate signBlob from iam.googleapis.com to iamcredentials.googleapis.com.
This API is deprecated and will be shutdown in one year.
This is used google.auth.iam.Signer.
Added a system_test to sanity check the implementation.

fix: migrate signBlob to iamcredentials.googleapis.com

---

.gitignore
google/auth/_default.py
google/auth/app_engine.py
google/auth/compute_engine/credentials.py
google/auth/credentials.py
google/auth/impersonated_credentials.py
google/auth/jwt.py
google/oauth2/credentials.py
google/oauth2/service_account.py
tests/compute_engine/test_credentials.py
tests/oauth2/test_credentials.py
tests/oauth2/test_service_account.py
tests/test__default.py
tests/test_app_engine.py
tests/test_credentials.py
tests/test_iam.py
tests/test_impersonated_credentials.py
tests/test_jwt.py
tests/transport/test_grpc.py
tests/transport/test_requests.py
tests/transport/test_urllib3.py

Make `quota_project_id` a property of the base credentials class and add it to the existing credentials types. 
Note that I didn't make `with_quota_project` an abstract method on the base credentials class because that would be a breaking change.
This PR also modifies functions in `default` to allow a `quota_project_id` to be passed.
```py
import google.auth
credentials, project = google.auth.default(quota_project_id='my-project')
```
```py
import google.auth
credentials, project = google.auth.load_credentials_from_file(
'service_account.json',
quota_project_id='my-project'
)
```

feat: add quota project to base credentials class

---

CONTRIBUTING.rst

Release-As: 1.19.2
Trying to get a release for #563

docs: add 3.8 support to contributing

---

google/auth/_helpers.py

Reduce clock skew from 5 minutes to 10 seconds, since metadata server token endpoint doesn't generate a new token until 30s before the expiration, it just returns the same token and the corresponding expires_in value. google-auth will keep calling token endpoint for around 4 minutes 30 seconds because of this.

fix: reduce refresh clock skew to 10 seconds

---

docs/reference/google.auth.transport.mtls.rst
google/auth/environment_vars.py
google/auth/transport/grpc.py
google/auth/transport/requests.py
google/auth/transport/urllib3.py
system_tests/test_mtls_http.py
tests/transport/test_grpc.py
tests/transport/test_requests.py
tests/transport/test_urllib3.py

Support this new env variable introduced in https://google.aip.dev/auth/4114

feat: add GOOGLE_API_USE_CLIENT_CERTIFICATE support

---

google/auth/app_engine.py
google/auth/compute_engine/credentials.py
google/auth/credentials.py
google/auth/impersonated_credentials.py
google/auth/jwt.py
google/oauth2/credentials.py
google/oauth2/service_account.py
tests/test__default.py
tests/test_credentials.py

https://github.com/googleapis/google-auth-library-python/pull/546#issuecomment-657876147
> Isn't this a breaking change? Should it have been released as 1.19.0?
> 
> We are already seeing test failures in downstream libs like `firebase-admin` where we extend this interface.
> 
> ```
> firebase_admin/db.py:983:0: W0223: Method 'with_quota_project' is abstract in class 'Credentials' but is not overridden (abstract-method)
> ```
https://github.com/googleapis/google-auth-library-python/pull/546#issuecomment-657883603
> 
> Actually this seems to be because pylint considers any method in an abstract class that throws NotImplementedError to be abstract: http://pylint-messages.wikidot.com/messages:w0223
> 
> Not quite sure if that should be considered a breaking change, or write it off as pylint …

refactor: split 'with_quota_project' into separate base class

---

google/auth/exceptions.py
google/oauth2/utils.py
setup.py
tests/oauth2/test_utils.py

This defines internal utilities to handle:
- OAuth client authentication
- Standard OAuth error response parsing into OAuthError exception.

feat: defines internal utils for OAuth client Auth and error handling

---

.gitignore
google/auth/iam.py
system_tests/test_service_account.py
tests/compute_engine/test_credentials.py
tests/test_iam.py

Reverts the revert in googleapis/google-auth-library-python#563.  (original PR is #553) This change is safe to take now that changes have been made internally.
(Copied from #553)
> Migrate signBlob from iam.googleapis.com to iamcredentials.googleapis.com.
> 
> This API is deprecated and will be shutdown in one year.
> 
> This is used google.auth.iam.Signer.
> Added a system_test to sanity check the implementation.

fix: "Revert "fix: migrate signBlob to iamcredentials.googleapis.com""

---

google/oauth2/credentials.py
tests/oauth2/test_credentials.py

This patch for </issues/501> includes the following fixes:
- The access token is always set to `None`, so the fix involves using (the access) `token` from the saved JSON credentials file.
- For refresh needs, `expiry` also needs to be saved via `to_json()`.
- DUMP: As `expiry` is a `datetime.datetime` object, serialize to `datetime.isoformat()` in the same [`oauth2client` format](https://github.com/googleapis/oauth2client/blob/master/oauth2client/client.py#L55) for consistency.
- LOAD: Add code to restore `expiry` back to `datetime.datetime` object when imported.
- LOAD: If `expiry` was unsaved, automatically set it as expired so refresh takes place.
- Minor `scopes` updates
- DUMP: Add property for `scopes` so `to_json()` can grab it
- LOAD: `scopes` may be saved as a string instead of a …

fix: fix expiry for `to_json()`

---

docs/reference/google.auth.transport.aiohttp_requests.rst
docs/reference/google.auth.transport.rst
google/auth/_jwt_async.py
google/auth/transport/_aiohttp_requests.py
system_tests/system_tests_async/conftest.py
tests_async/oauth2/test__client_async.py
tests_async/test_jwt_async.py
tests_async/transport/test_aiohttp_requests.py

Moving async to `_aiohttp_requests` and `_jwt_async` as these surfaces aren't finalized. This should allow merging this branch to the main branch.

fix: move async to internal surface until stabilized

---

google/auth/impersonated_credentials.py
tests/test_impersonated_credentials.py

fix: expiry in impersonated_credentials.IDTokenCredentials
