googleapis/google-auth-library-python

- google/auth/exceptions.py
- google/auth/transport/__init__.py
@dhermes you've already mostly review this.
> Add google.auth.transport and google.auth.exceptions

- google/auth/__init__.py
- google/auth/compute_engine/_metadata.py
- google/auth/transport/_http_client.py
- google/auth/transport/urllib3.py
> Setup logging

- .travis.yml
> Add pypy to travis

- google/auth/_service_account_info.py
- google/auth/jwt.py
- google/oauth2/service_account.py
- tests/oauth2/test_service_account.py
- tests/test__service_account_info.py
- tests/test_jwt.py
> Consolidate service account file loading logic.

- google/oauth2/service_account.py
- tests/oauth2/test_service_account.py
> Add service_account.Credentials.to_jwt_credentials

- google/auth/_cloud_sdk.py
- tests/test__cloud_sdk.py
> Read cloud sdk active_config file to determine the right config file to read

- system_tests/conftest.py
- system_tests/test_compute_engine.py
- system_tests/test_default.py
- system_tests/test_oauth2_credentials.py
- system_tests/test_service_account.py
> Adding ADC system tests

- system_tests/test_compute_engine.py
- system_tests/test_default.py
> Add test for GCE default credentials

- httplib2_transport/google_auth_httplib2.py
- httplib2_transport/setup.py
- httplib2_transport/tests/test_google_auth_httplib2.py
> Add proxy to httplib2.Http.connections

- CHANGELOG.rst
- setup.py
> Release v0.6.0

- google/oauth2/credentials.py
- tests/oauth2/test_credentials.py
> Add public properties to google.oauth2.credentials.Credentials

- system_tests/nox.py
> Update gcloud in system tests

- CHANGELOG.rst
- setup.py
(or the "I'm so close to v1.0.0 I can taste it" release)
> Release v0.10.0

- docs/user-guide.rst
> Documentation Update: Added instructions for using the library in App Engine

- google/auth/compute_engine/_metadata.py
> low effort typo fix

- docs/user-guide.rst
- google/oauth2/service_account.py
- tests/oauth2/test_service_account.py
> Expose Project ID from service account credentials

- google/auth/app_engine.py
- tests/test_app_engine.py
Resolves https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3937
> Fix App Engine's expiration calculation

- google/auth/credentials.py
- tests/test_credentials.py
See: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4279.
/cc @jonparrott
> Add 'AnonymousCredentials' class.

- google/oauth2/service_account.py
- tests/transport/test__http_client.py
I assume this is what it was supposed to be 😄
> fix comment, seconds not sections

- MANIFEST.in
> Exclude compiled Python files in source distributions

- google/auth/transport/requests.py
Setting timeout only to the requests library. Backward compatible.
Much simpler than my previous PR (#205) because I've made my misuderstanding clear.
I said:
> the users of this library cannot determine whether the exception is from the token refresh HTTP requests (which I think can be safely retried) or from their own ones (which might not be idempotent nor able to be retried).
But it is not true. `refresh()` raises `google.auth.exceptions.TransportError` wrapping a requests' exception.
So users can write retry logic like
```python
try:
request()
except google.auth.exceptions.TransportError as e:
if isinstance(e.args[0], requests.exceptions.ReadTimeout):
retry()
```
> google.auth.transport.requests: make credential refresh robust

- google/auth/_default.py
- tests/test__default.py
Resolves GoogleCloudPlatform/google-auth-library-python#221
> Check for project_id envvar before warning

- google/auth/credentials.py
> Fix a typo in credentials.py.

- docs/index.rst
> Fix links to README and CONTRIBUTING in docs/index.rst

- renovate.json
Preempt default pinning config.
Supersedes #354.
> Initial renovate config.

- README.rst
An attempt to reduce the number of pings Luke and Thea get for auth library questions.
> docs: add busunkim96 as maintainer

- README.rst
- setup.py
These were left behind and make the upload to PyPI fail (invalid RST for long description)
> chore: remove unused badges, update author_email

- google/auth/transport/requests.py
- noxfile.py
- tests/transport/test_requests.py
> feat: add timeout parameter to AuthorizedSession.request()

- google/auth/_default.py
- tests/test__default.py
> fix: don't add empty quota project 

- .gitignore
- google/auth/iam.py
- system_tests/test_service_account.py
- tests/compute_engine/test_credentials.py
- tests/test_iam.py
Reverts googleapis/google-auth-library-python#553
We have received reports that this is breaking users. See internal issue 161506225.
> Revert "fix: migrate signBlob to iamcredentials.googleapis.com"

- tests/oauth2/test_credentials.py
- tests/oauth2/test_service_account.py
> test: add more tests for service account quota projects

- docs/reference/google.auth.compute_engine.rst
- docs/reference/google.auth.crypt.rst
- docs/reference/google.auth.rst
- docs/reference/google.auth.transport.rst
- docs/reference/google.oauth2.rst
- docs/reference/google.rst
- noxfile.py
- setup.py
Release-As: 1.20.0
Closes #568
> feat(packaging): add support for Python 3.8

- google/auth/credentials.py
trigger an auto release for #561
> fix: trigger an auto release

- tests/test_external_account.py
Forgot to commit this small naming change.
> test: fix test_external_account.py constant name
